PRAGMA foreign_keys = ON;

CREATE  TABLE IF NOT EXISTS Something (
  id INTEGER PRIMARY KEY ASC,
  otherId INTEGER,
  data INTEGER,

  FOREIGN KEY (otherId) REFERENCES Other(id)
);

CREATE TABLE IF NOT EXISTS Other (
  id INTEGER PRIMARY KEY ASC,
  data VARCHAR(40) UNIQUE
);